# Generated by Django 4.0.4 on 2022-06-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationRowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='None', max_length=30, verbose_name='symbol')),
                ('entrezID', models.CharField(default='None', max_length=50, verbose_name='entrezID')),
                ('uniprotID', models.CharField(default='None', max_length=50, verbose_name='uniprotID')),
                ('ensemblID', models.CharField(default='None', max_length=50, verbose_name='ensemblID')),
                ('doid', models.CharField(default='None', max_length=30, verbose_name='doid')),
                ('source', models.CharField(default='None', max_length=30, verbose_name='source')),
                ('diseaseName', models.TextField(default='None', verbose_name='diseaseName')),
                ('doidSource', models.CharField(default='None', max_length=10, verbose_name='doidSource')),
            ],
            options={
                'unique_together': {('symbol', 'entrezID', 'uniprotID', 'ensemblID', 'doid', 'source', 'diseaseName',
                                     'doidSource')},
            },
        ),
    ]
