# Generated by Django 4.0.4 on 2022-06-29 10:27

from django.db import migrations
import pandas as pd

# TODO: move constant
ANNOTATION_FILE_PATH = "annotationFile.txt"


def delete_rows(apps, scheme_editor):
    AnnotationModel = apps.get_model('GDA_datatables', 'AnnotationRowModel')
    for row in AnnotationModel.objects.all():
        row.delete()


def forwards(apps, schema_editor):
    AnnotationModel = apps.get_model('GDA_datatables', 'AnnotationRowModel')
    data = pd.read_csv(ANNOTATION_FILE_PATH, sep='\t').to_numpy()
    for row in data:
        AnnotationModel.objects.create(symbol=str(row[0]),
                                       entrezID=str(row[1]),
                                       uniprotID=str(row[2]),
                                       ensemblID=str(row[3]),
                                       doid=str(row[4]),
                                       source=str(row[5]),
                                       diseaseName=str(row[6]),
                                       jaccardIndex=str(row[7])
                                       )


class Migration(migrations.Migration):

    dependencies = [
        ('GDA_datatables', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_rows),
        migrations.RunPython(forwards),
    ]
