version: "3.9"
services:
  typesense:
    image: typesense/typesense:0.22.2
    container_name: typesense
    logging:
      driver: none
    ports:
      - "8108:8108"
    environment:
      TYPESENSE_API_KEY: "1"
      TYPESENSE_DATA_DIR: /data/typesense
    volumes:
      - typesense:/data/typesense
  gda:
    image: gda:1.0
    container_name: gda
    volumes:
      - gda:/Storage
    ports:
      - "8000:8000"
volumes:
  typesense:
    driver: local
  gda:
    driver: local