#
# GDA Copyright (c) 2022.
# University of Belgrade, Faculty of Mathematics
# Luka Milosevic
# lukamilosevic11@gmail.com
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#

version: "3.9"
services:
  typesense:
    image: typesense/typesense:0.22.2
    container_name: typesense
    logging:
      driver: none
    ports:
      - "8108:8108"
    environment:
      TYPESENSE_API_KEY: ${API_KEY}
      TYPESENSE_DATA_DIR: /data/typesense
    volumes:
      - typesense:/data/typesense
  gda:
    depends_on:
      - typesense
    image: lukamilosevic11/gda:latest
    container_name: gda
    environment:
      API_KEY: ${API_KEY}
    volumes:
      - ./Storage:/GDA/GDA_backend/Storage
      - gda:/GDA/GDA_frontend/Database
    ports:
      - "8000:8000"
volumes:
  typesense:
    driver: local
  gda:
    driver: local